### ISSUE TITLE
Question about autocomplete

### ISSUE THREAD

**Issue by adanilovich** [FractalBoy/perl-language-server#101]
Hi, I am not confident that these issues due to bugs on the pls side. 
In general, I have got a little perl script, which will be below. I encountered with couple strange issues. I enumerate them in order. 
1. It doesn't work the autocomplete for LWP::Useragent package. I don't realize why, because I pointed  the inc option e.g  `inc = {'/usr/share/perl5/core_perl','/usr/share/perl5/vendor_perl/CPAN', '/usr/share/perl5/site_perl'}, `
2. It doesn't work the autocomplete for following code when I type `$bot->`, but work for `HTTP::tiny->`
```
my $url=$ARGV[0];
my $bot=HTTP::Tiny->new();
$bot->agent("simple bot");
my $resp=$bot->get($url);
$resp->{content} =~ q|<title>(.*?)</title>|;
print "$ARGV[0]| title -> $1";
```

**Comment by FractalBoy** [comment]
Did you type LWP::Useragent or LWP::UserAgent? LWP::UserAgent is the correct name.

Autocomplete works for me with that package:

![image](https://user-images.githubusercontent.com/2024233/170149626-5120c44c-c0fc-4b71-917b-daccdf0f31a8.png)

As for the second question, that is not intended to work - it is not easy to tell what type `$bot` is without running the code. It is not impossible, I just think it will be time consuming to determine. Currently, autocomplete is based on indexing of every file in the project as well as functions found by importing a module and inspecting it using typeglobs, which is fast.

In order to determine the type of `$bot`, I'd have to use PPI to find the declaration (or a later assignment) of a variable and guess the package based on that. This wouldn't work for functions where you pass an object as a parameter since the object construction would happen elsewhere.

https://github.com/bscan/PerlNavigator supposedly does this, so you can try that project and see if it works for you.
