### ISSUE TITLE
Option for disabling processId checks

### ISSUE THREAD

**Issue by mbudde** [FractalBoy/perl-language-server#118]
a7cfe2abe6964d237a84f369709e9441f52ac1c4 added code that checks if the client is still alive and exits the server process if not. This is problematic for me, since I'm running PLS inside a docker container, which means that PLS exits 30 seconds after it starts when it fails to find the client process.

Would you be open to adding an option that disables this check, or do you have some other suggestion on how this setup could be made to work?

I'll be happy to provide a PR that adds an option.

**Comment by FractalBoy** [comment]
I think we can just pull it - feel free to submit a PR that removes the check.

It wasn't always there - I only added it as a precaution because the LSP docs say this. I don't know that it actually provides any utility.

> To support the case that the editor starting a server crashes an editor should also pass its process id to the server. This allows the server to monitor the editor process and to shutdown itself if the editor process dies. The process id pass on the command line should be the same as the one passed in the initialize parameters. The command line argument to use is --clientProcessId.

**Comment by AlexTalker** [comment]
@FractalBoy Could you please publish the new release containing this fix on CPAN? I just debugged problem of running server via SSH onto this same issue and I build your project from latest CPAN release =)

**Comment by FractalBoy** [comment]
@AlexTalker - yes, I have been meaning to do a release. I'll try to do one this week or weekend.

**Comment by AlexTalker** [comment]
@FractalBoy Nice, thank you. Also, this is a bit off-topic and probably requires a separate issue but after I fixed the bug locally, completion began to work somewhat like a charm but I miss one behavior.

Say, one writes:
```perl
use AnyEvent::Util qw(
);
```
and then proceeds to fill in imports:
```perl
use AnyEvent::Util qw(
    fork_<pressing Ctrl-Space>
);
```

One expects to get completion for available imports but unfortunately currently this approach yields nothing.

I feel like it might be pretty handful to handle, since you already can complete imported names.

(The expected result is to complete to `fork_call`, see [the original](https://metacpan.org/release/MLEHMANN/AnyEvent-7.17/source/lib/AnyEvent/Util.pm))

**Comment by FractalBoy** [comment]
Yes, I'd like that feature as well. Please create a new issue.
