### ISSUE TITLE
Couldn't start client Perl Language Server (PLS)

### ISSUE THREAD

**Issue by niceperl** [FractalBoy/perl-language-server#52]
I got this message after instaling the plugin on VS Code - Windows 10
(PLS v 0.88 installed)

Details:
```
[Error - 8:20:13] Starting client failed
Launching server using command pls failed.
```

**Comment by arulprakash8806** [comment]
facing same issue

**Comment by FractalBoy** [comment]
Please share any errors you see in the output window.

**Comment by niceperl** [comment]
> Please share any errors you see in the output window.
I wrote down all the text in the output window:
```
[Error - 8:20:13] Starting client failed
Launching server using command pls failed.
```

**Comment by FractalBoy** [comment]
There's not much here for me to go on. You said this was Windows.

* Are you running PLS on Windows as well, or using a Remote-SSH or WSL extension?

* What happens if you run `pls` at the command line? If the command is not pls, you will need to modify your configuration to use the correct path.

Keep in mind this has not been tested on Windows so I don't really expect it to work there. I need someone enterprising enough who uses Perl on Windows to address all the Windows bugs, as I don't have a development environment to test this on.

**Comment by arulprakash8806** [comment]
`[Error - 12:43:37 PM] Starting client failed
Launching server using command pls failed.`

`pls` is added to my PATH. I'm trying to run `pls` via Remote-SSH. I'm able to launch `pls` on the terminal.

**Comment by arulprakash8806** [comment]
I was able to launch it. I had to give the absolute path of `pls` in settings like /home/<usr_name>/<pls_path>

**Comment by FractalBoy** [comment]
The pls script should not be in your path. It needs to be the bin directory where the script is located.

The easiest way to use PLS is to install it via CPAN.

**Comment by FractalBoy** [comment]
@niceperl Are you still having this issue?

**Comment by niceperl** [comment]
Yes, I have.
I have Strawberry Perl 5.30. From a console:
```
%> where pls
C:\Perl\perl\site\bin\pls
C:\Perl\perl\site\bin\pls.bat

%> pls
[... command is running ... by the way, Ctrl+C crash it ]
```

Do I have to configure the VS extension? I didn't do anything of that

**Comment by FractalBoy** [comment]
Okay, I will need to get a Windows environment set up to debug this.

I likely won't have time to do so until next week at the earliest.

The one thing I would suggest trying in the meantime is putting the full path to pls in your perl.pls configuration.

**Comment by niceperl** [comment]
I found the solution: at Perl Pls (Path to the pls executable script), I wrote `pls.bat` instead of `pls`
Windows has no idea what to do with `pls` because it doesn't interprete the seebang line.
I don't know if you can change that on the VS code extension (taking into account the operating system in the config defaults)

**Comment by FractalBoy** [comment]
Ah, good find. And no, I don't think the default can be changed, but the code can probably be changed to add .bat to the end of the command if running on Windows and .bat isn't already there.

**Comment by FractalBoy** [comment]
https://github.com/microsoft/vscode/issues/5595

**Comment by PPetky** [comment]
Hi!
```
[Error - 13:27:32] Starting client failed
Launching server using command pls failed.
```
I'm trying to use it via ssh. I have run Perl::LanguageServer on ssh and it work after some time of configuring.
I wonder, if there a how-to doc 

BRG, Peter

**Comment by FractalBoy** [comment]
I need more information. Please share your PLS configuration.

**Comment by PPetky** [comment]
> I need more information. Please share your PLS configuration.

Sure
```
{
    "perl.pls": "ssh",
    "perl.plsargs": ["-l", "user", "-p", "22", "server.local", "'pls'"]
}
```

**Comment by FractalBoy** [comment]
Neither of those will work (see #36).

Unless you want to try fixing #36 yourself, you will need to create a shell script that you can execute to do the ssh.

Not sure where you got the idea that plsargs is an option.

**Comment by PPetky** [comment]
> Neither of those will work (see #36).
> 
> Unless you want to try fixing #36 yourself, you will need to create a shell script that you can execute to do the ssh.
> 
> Not sure where you got the idea that plsargs is an option.

Well, I'm not so cool Perl programmer.... But anyway, I wrote a shell script, it connects me to remote PLS,
but when I try to references e.g. [F12], I got this below
```
mkdir /home/my_local_username: Permission denied at /usr/local/share/perl/5.26.1/PLS/Parser/Index.pm line 51.
```

**Comment by FractalBoy** [comment]
PLS creates a file in your project directory which stores references in your project. Since your ssh session doesn't have access to it, it doesn't work.

I recommend using the VSCode Remote-SSH extension instead of doing this.

**Comment by stphnlyd** [comment]
I get the same issue: 
* on Linux I have to specifiy absolute path to perl.pls, same as what @arulprakash8806 said
* on Windows even setting the full path to pls.bat does not work..

**Comment by FractalBoy** [comment]
@stphnlyd are you getting the same error?

I'm not surprised that it wouldn't work on Windows. I tried running unit tests on Windows and it failed for some reason that I never understood. 

Given that I don't do development on Windows, I would really need someone enterprising to get PLS to be fully compatible with Windows.

**Comment by FractalBoy** [comment]
Workspace symbols aren't supported.

What do you mean by empty?Workspace symbols are opt in by the server, so VSCode shouldn't even display it as an option.

What do you hope to accomplish with that option that isn't provided by document symbols?

**Comment by cblake777** [comment]
We have a fairly large library of modules.  There are times where I know the name of the method I'm looking for, but I don't recall exactly which module it is located in.  In sublime text, this is a fairly easy "search all the files and find any methods where it fuzzy matches X", I'm trying to replicate that functionality.  Perl::LanguageServer technically does it, but well, among other concerns, it's is frustratingly case-sensitive. 

As far as empty, I simply meant that if I bring up the "Go to Symbol in Workspace (ctrl+t)" option under Edit, the list there is empty :)

As a follow-up to everything.  The symbols in the document seem to work perfectly fine, at first.  Unfortunately, they just *stop* working after a while.  In my testing, it coincidentally appears to be related whatever indexing VS Code does when it is first launched.  As I mentioned, we have a fairly large library, and when VS Code tries to index the files in the workspace, it takes a decent chunk of time (it's one of the reasons I've still stick with Sublime, it handles that indexing differently). The delay is most likely because it's a remote mount via sshfs (we can't use the Remote-SSH extension because the hosts are too old to support it).  I say all this because while the indexing of those files is happening, the "Go To File" option doesn't really return any results. During this time, any files I manually open via the file tree are able to have their symbols identified.  However, after a bit, I notice that the indexing finished and I am able to make use of "Go to file", which appears to be when the symbols stop working.  Under the "Outline" section I just see a message saying "loading symbols" (or something of that sort), and, any previously open files that were working now are not, and display the same message. I don't know that the two events are actually related, it seemed to happen around the same time.
