### ISSUE TITLE
visible tempfiles while running on an nfs shared folder

### ISSUE THREAD

**Issue by oetiker** [FractalBoy/perl-language-server#60]
PLS 0.895

It seems that PLS generates files which it keeps open and immediately deletes again ... on an nfs shared folder this has the effect of creating .nfs files ... this is nothing 'bad' but it is rather ugly ... I would rather like to see these things be generated /tmp or /run/shm as this is generally local or even in memory and above all out of sight ... 

![image](https://user-images.githubusercontent.com/429279/128349707-26107ea1-3868-498f-b0d5-4ea433991cf1.png)

It also seems that all these different `.nfs*` files are actually copies of the file I am currently working on ... and the fact that they are still around indicates that PLS is keeping them open ... and thus prevents their removal.

**Comment by FractalBoy** [comment]
The files are used to perform syntax checking and linting as you type instead of just when you save.

I would also prefer they be created in /tmp, however the code base I work on every day is very sensitive to file location and syntax checking just doesn't work for me if I put the files elsewhere.

PLS should be creating files in temp directories but with the same file names as the original file. When I am working the files are created and deleted.

I'm not an expert in NFS, so I don't know why these extra .nfs files are created as well, can you shed some light on that? I'd be more than happy to put in some extra code to make sure that those files are cleaned up as well.

As a side note, you can configure VSCode to hide hidden files (files starting with .) from the sidebar.

**Comment by oetiker** [comment]
On unix, when you keep a filehandle open to a file you have removed, your process still has access to that file. It only gets deleted from the filesystem once the last filehandle to the file is closed. This is why you can delete a file using 'rm' despite it being hold open by some process.

When working with nfs, this behavior also exists, except that NFS can not deal with a file that has no entry in the directory structure. So when you rm a file which is still open by some programm, instead of removing the file, it gets renamed to .nfsXXXXXXX and once the last program closes its filehandle then the .nfsXXXXX file gets removed ... 

From what you write I get the impression that you maybe simply have a filedescriptor leak in your code ... :)

**Comment by FractalBoy** [comment]
Interesting. I'm not sure where I would be leaking since I pretty consistently close my filehandles (and perl will do it for you when your filehandle goes out of scope if you forget)

The only possibility I can think of is that the long running IO::Async::Function that runs perlcritic is keeping the handles open. I have an idea for a workaround, though.

Would you be able to test a patch? I don't have an NFS server to test on.

**Comment by FractalBoy** [comment]
Can you try this branch and let me know how it works for you?

https://github.com/FractalBoy/perl-language-server/tree/gh-60-nfs-temp-files

You can build and install with these commands:

```
perl Makefile.PL
make
make install
```

To reinstall the version from CPAN, you can reinstall using cpanm --reinstall PLS, if you are using cpanm.

**Comment by oetiker** [comment]
I tried your patch ... it is better now, the leak seems to be gone ... there is still the fact that folders with random directory names pop up in the current directory and in that folder is a temp copy of the file, but after checking they disappear again ... still wondering why this has to happen in  the current directory :) if the folder names had a prefix like .pls-tmp-XXXXX or something then they could be excluded using a glob rule in VC ...

**Comment by FractalBoy** [comment]
That's a good idea. I will add a prefix, like you suggest.

**Comment by oetiker** [comment]
Another thought ... there might also be a sort of race condition when removing the file ... if the whole thing happens on nfs ... if the file is not closed when you remove it, it will get renamed to `.nfsXXXX` and then you not be able to remove the directory containing the file as the directory is not empty. Removing the .nfsXXXX file will also not work, as it will simply get renames to .nfsXXXYYY or something ...

So it is really important that the file is closed by all parties when you remove it ...

**Comment by FractalBoy** [comment]
In the patch, the file is only open for a short period of time: to write out text and by `perl -c`.

Once both of those are done, the entire directory is cleaned up.

I don't see how the file could still be open at that point.

**Comment by oetiker** [comment]
Yes I did not see the problem with the patch ... I just wanted to make sure you understood the behavior ... as it is a bit unintuitive if one is used to the normal behavior on a local file system.

**Comment by FractalBoy** [comment]
Yes, I understand. And as a rule, I try to close filehandles as soon as possible after opening them (Perl::Critic::Policy::InputOutput::RequireBriefOpen helps with this)

I think the issue was that there is a long running perl process that uses Perl::Critic and it was holding onto the filehandle for some reason (something I have no control over). As a workaround, I passed the source code as a SCALAR ref instead of the filename, and restricted the temporary file to checking syntax, which requires a filename.
