### ISSUE TITLE
Implement support for workspace folders

### ISSUE THREAD

**Issue by carlosfrodriguez** [FractalBoy/perl-language-server#82]
I can confirm that the extension is working as PerlCritic, PerlTidy, Outline and Syntax check are working correctly and without issues. but for me Go to definition is not really working for me in VSCode...

I always get something similar to `No definition found for 'Foo'`.

I'm not sure how can I help to debug, but I will be happy to follow any instructions and or provide any needed configuration o information.

((enjoy))
cr

**Comment by FractalBoy** [comment]
Are you working in a folder, workspace, or file?

Do you see anything in the output window if you select PLS from the dropdown?

**Comment by carlosfrodriguez** [comment]
Hi, I'm working in a workspace and actually I see no `PLS` item in the output dropdown list.

**Comment by FractalBoy** [comment]
Can you try using a folder instead of workplace and let me know if that works? I haven't implemented support for workspaces yet.

**Comment by carlosfrodriguez** [comment]
Yes it works with a single root folder, I hope you can implement workspace support

**Comment by FractalBoy** [comment]
I would like to, but it requires some thought and attention into making sure I get it right, which I need to find the time for.

**Comment by FractalBoy** [comment]
Thanks! The main challenge will be managing the cache, since it is currently stored in the project directory. So you'd need to either pick a new place to store the cache or find a way to manage multiple caches. 

I believe that VSCode provides directories that can be used for per-workspace data but I'm not sure what the support looks like in other editors. And I'm not entirely sure how to expose that via the LSP.

**Comment by FractalBoy** [comment]
Closed via #109
