### ISSUE TITLE
PLS client stopps working after VSCode update to 1.64

### ISSUE THREAD

**Issue by mbuc82** [FractalBoy/perl-language-server#84]
Hello,

i've recently updated VSCode to January version 1.64, which resulted in errors regarding the PLS extension.

Error messages after start are:

```
[Error - 17:46:00] Starting client failed
Launching server using command pls failed.
```

Obviously there are changes to the language server protocol introduced, please see the [release notes](https://code.visualstudio.com/updates/v1_64#_language-server-protocol)

Unfortunately also removing the caches from my workspaces and restarting the machine didn't help here.
To me it seems, it has something to do with the client code (not the perl server), as it keeps working in an older release.

I'm currently using VSCode with PLS on two Arch Linux machines, where one works (VSCode 1.63) and the other doesn't (1.64).

Thanks in advance for your help!

Cheers
Marco

**Comment by FractalBoy** [comment]
I don't expect that they would introduce breaking changes to the language server protocol.

There must be something else that is wrong. That error is usually because the pls script cannot be started.

It seems like your configuration is wrong and PLS (the VSCode extension) is configured to point to an invalid pls (the script).

**Comment by mbuc82** [comment]
You're right, for some reason the pls binary won't be found anymore after the update. If i add the path explicitly with `perl.pls` it's working again.

Thanks a lot, i'm closing the issue.
