### ISSUE TITLE
Trouble getting perlcriticrc to work for linting in Neovim

### ISSUE THREAD

**Issue by CharlesARoy** [FractalBoy/perl-language-server#87]
Hello, I'm having a hard time getting linting to work with perlcriticrc and any pointers would be appreciated. With my current setup, I'm at least getting Perl autocomplete suggestions, so I know I'm almost there.

E.g.:
![image](https://user-images.githubusercontent.com/46253001/155034637-49e3bf96-d086-4242-bd5a-1978bdb575cb.png)

![image](https://user-images.githubusercontent.com/46253001/155034685-c2894457-cacf-463a-b089-096af2b74dff.png)

My Neovim config looks like:
```
├── init.lua
├── lua
│   └── user
│       ├── alpha.lua
│       ├── autocommands.lua
│       ├── autopairs.lua
│       ├── bufferline.lua
│       ├── cmp.lua
│       ├── colorscheme.lua
│       ├── comment.lua
│       ├── gitsigns.lua
│       ├── icons.lua
│       ├── impatient.lua
│       ├── indentline.lua
│       ├── keymaps.lua
│       ├── lsp
│       │   ├── handlers.lua
│       │   ├── init.lua
│       │   ├── lsp-installer.lua
│       │   ├── null-ls.lua
│       │   ├── perlpls.lua
│       │   └── settings
│       │       ├── jsonls.lua
│       │       └── sumneko_lua.lua
│       ├── lualine.lua
│       ├── nvim-tree.lua
│       ├── options.lua
│       ├── plugins.lua
│       ├── project.lua
│       ├── telescope.lua
│       ├── toggleterm.lua
│       ├── treesitter.lua
│       └── whichkey.lua
└── plugin
    └── packer_compiled.lua
```

The init.lua file in the top directory requires the lsp directory which contains an init.lua file. That init.lua file looks like this:
![image](https://user-images.githubusercontent.com/46253001/155034925-ddb45dd7-4f78-4bac-96ce-a6dfe924e45d.png)

It requires the user.lsp.perlpls file which has this for content:
![image](https://user-images.githubusercontent.com/46253001/155035616-5081eb4a-87c6-4c44-abb1-a83befdb7188.png)

Per the perl-language-server documentation, I installed the PLS, using the information [at this link](https://metacpan.org/pod/PLS) and ran `cpanm PLS` to install it. 

Note, for all other language servers, I installed them using the [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer), but unfortunately it doesn't support Perl. 

My hope is that with Perl linting, I'll be able to get behavior like I have with Python, including goto definition, hover, etc.
![image](https://user-images.githubusercontent.com/46253001/155036464-69bcf48d-fa41-49ca-a049-192c389486be.png)

**Comment by FractalBoy** [comment]
I don't use Neovim, so I don't think I'll be of much help here. I don't think I was able to get it work the one time I tried.

@WhoIsSethDaniel contributed the instructions for how to use Neovim - can you help?

**Comment by WhoIsSethDaniel** [comment]
Hi @CharlesARoy. I may be able to help you. I use `pls` and `perlcritic` is working fine.  

If you run `perlcritic` on a perl file do you receive output?  What is it?

If you then use `pls` to work on the file do you not see the same errors?

Are you using a `perlcrticrc` file?

I assume you have `Perl::Critic` installed since `pls`  requires `Perl::Critic` as a dependency. 

If we start with a simple example: a single file in its own directory. Call it `pc.pl` with the following contents:
```
#!/usr/bin/env perl

print "hello there."
```
If you now run `perlcritic` on it you should see an error:
```
$ perlcritic pc.pl
Code before strictures are enabled at line 3, column 1.  See page 429 of PBP.  (Severity: 5)
```
If you then edit this file with neovim you should see the error in-line (typically in red, but may be different based on your theme -- I'm also assuming you have a default LSP configuration that has virtual text turned on). 
Verify that PLS is running.

If you do not see an error when running `perlcritic` than something is wrong with your `perlcritic` installation. Or you have a `perlcriticrc` file lying around that has non-default rules.

If you continue to have problems please let us know what version of neovim you are running and what plugins you are using with it. You may try to whittle down the plugins to see if one of them is causing problems. Perhaps just use `lspconfig` while testing.  Since you seem to be able to get python to work with `lspconfig` this _probably_ isn't the problem, but better safe than sorry.

**Comment by CharlesARoy** [comment]
Thanks so much for the detailed response @WhoIsSethDaniel !

It took me a bit but I got it figured out.

First off (and I know this isn't ideal), my Neovim config is based on the setup Chris@Machine describes in [these videos](https://www.youtube.com/watch?v=ctH-a-1eUME&list=PLhoH5vyxr6Qq41NFL4GvhFp-WLd5xzIzZ
) (repo [here](https://github.com/LunarVim/Neovim-from-scratch)), and I'm still figuring out some of the details behind the config.

First, I reorganized my setup slightly to the following (moving `perlpls.lua` to the settings directory):

```
tree
.
├── init.lua
├── lua
│   └── user
│       ├── alpha.lua
│       ├── autocommands.lua
│       ├── autopairs.lua
│       ├── bufferline.lua
│       ├── cmp.lua
│       ├── colorscheme.lua
│       ├── comment.lua
│       ├── gitsigns.lua
│       ├── icons.lua
│       ├── impatient.lua
│       ├── indentline.lua
│       ├── keymaps.lua
│       ├── lsp
│       │   ├── handlers.lua
│       │   ├── init.lua
│       │   ├── lsp-installer.lua
│       │   ├── null-ls.lua
│       │   └── settings
│       │       ├── jsonls.lua
│       │       ├── perlpls.lua
│       │       └── sumneko_lua.lua
│       ├── lualine.lua
│       ├── nvim-tree.lua
│       ├── options.lua
│       ├── plugins.lua
│       ├── project.lua
│       ├── telescope.lua
│       ├── toggleterm.lua
│       ├── treesitter.lua
│       └── whichkey.lua
└── plugin
    └── packer_compiled.lua
```

I then required the user.lsp.settings.perlpls file in the init.lua file in the lsp directory (which contains the following):
![image](https://user-images.githubusercontent.com/46253001/155045661-e9a933a8-3724-4349-afa3-e8c72df02d47.png)

Then, I configured the perlpls.lua file like this:
![image](https://user-images.githubusercontent.com/46253001/155046389-d2b601de-4895-450d-b66c-eef4d54aff7c.png)

Turns out that the reason linting wasn't working had to do with a part of Chris' config that I didn't (and still don't) understand very well, which is his [handlers.lua](https://github.com/LunarVim/Neovim-from-scratch/blob/master/lua/user/lsp/handlers.lua) file. Anyway, as I understand it, the on_attach and capabilities functions are loaded from the handlers.lua file and then added to the perlpls config settings with the vim.tbl_deep_extend command. Finally, the perlpls language server is setup with the local config and perl opts.
